Repository capgoing/BE, pull requests merged in 2025-04, with the labels that each got.

#40 🐛 [Fix] @PostConstruct 제거
  src/main/java/com/going/server/global/temp/service/FastApiService.java
Labels: :earth_asia: Deploy

#41 ⚡️ [Perf] FastAPI 클러스터링 결과 저장 로직 성능 개선
  src/main/java/com/going/server/global/temp/service/FastApiService.java
Labels: :earth_asia: Deploy

#56 🛠 [config] Spring Boot - React 통신을 위한 CORS 및 Nginx 설정
  src/main/java/com/going/server/global/config/SwaggerConfig.java
Labels: ⚙ Setting

#60 ✨ [feat] 퀴즈 생성 api 구조 셋팅 (listenUp 모드)
  src/main/java/com/going/server/domain/quiz/controller/QuizController.java
  src/main/java/com/going/server/domain/quiz/dto/ConnectQuizDto.java
  src/main/java/com/going/server/domain/quiz/dto/ListenUpQuizDto.java
  src/main/java/com/going/server/domain/quiz/dto/PictureQuizDto.java
  src/main/java/com/going/server/domain/quiz/dto/QuizCreateResponseDto.java
  src/main/java/com/going/server/domain/quiz/service/QuizService.java
  src/main/java/com/going/server/domain/quiz/service/QuizServiceImpl.java
Labels: :sparkles: Feature, ⚙ Setting

#61 ✨ [feat] 지식그래프 퀴즈 생성을 위한 기본 세팅 및 로직 구현
  src/main/java/com/going/server/domain/graph/entity/Graph.java
  src/main/java/com/going/server/domain/graph/exception/GraphErrorCode.java
  src/main/java/com/going/server/domain/graph/exception/GraphNotFoundException.java
  src/main/java/com/going/server/domain/graph/repository/GraphRepository.java
  src/main/java/com/going/server/domain/quiz/controller/QuizController.java
  src/main/java/com/going/server/domain/quiz/dto/QuizCreateResponseDto.java
  src/main/java/com/going/server/domain/quiz/service/QuizService.java
  src/main/java/com/going/server/domain/quiz/service/QuizServiceImpl.java
Labels: :sparkles: Feature

#63 ✨ [feat] 지식그래프 관련 Entity 생성 및 Mock Data 삽입
  docker-compose.yml
  src/main/java/com/going/server/domain/graph/entity/Graph.java
  src/main/java/com/going/server/domain/graph/entity/GraphEdge.java
  src/main/java/com/going/server/domain/graph/entity/GraphNode.java
Labels: :sparkles: Feature

#82 ✨[feat] Connect Quiz 생성 로직 구현 & ♻️[refact] Quiz 생성 로직 리팩터링(strategy 패턴 적용)
  src/main/java/com/going/server/domain/quiz/dto/ConnectQuizDto.java
  src/main/java/com/going/server/domain/quiz/generate/ConnectQuizGenerator.java
  src/main/java/com/going/server/domain/quiz/generate/ListenUpQuizGenerator.java
  src/main/java/com/going/server/domain/quiz/generate/PictureQuizGenerator.java
  src/main/java/com/going/server/domain/quiz/generate/QuizGenerator.java
  src/main/java/com/going/server/domain/quiz/service/QuizServiceImpl.java
Labels: :sparkles: Feature, 🔨 Refactor

#84 ✨ [feat] Picture Quiz 생성 로직 구현 API
  src/main/java/com/going/server/domain/quiz/dto/PictureQuizDto.java
  src/main/java/com/going/server/domain/quiz/exception/QuizErrorCode.java
  src/main/java/com/going/server/domain/quiz/exception/QuizImageException.java
  src/main/java/com/going/server/domain/quiz/exception/UnsupportedQuizModeException.java
  src/main/java/com/going/server/domain/quiz/generate/ListenUpQuizGenerator.java
  src/main/java/com/going/server/domain/quiz/generate/PictureQuizGenerator.java
  src/main/java/com/going/server/domain/quiz/service/QuizServiceImpl.java
Labels: :sparkles: Feature

#95 Bug/#93
  .github/workflows/CICD.yml
Labels: :bug:bug, :earth_asia: Deploy

#96 🐛 [fix(ci)] : plain jar 제외하고 실행 가능한 jar만 업로드 및 복사하도록 수정
  .github/workflows/CICD.yml
  Dockerfile
Labels: :bug:bug

#99 🐛 [fix(ci)] CI/CD에서 bootJar 결과물 명시적으로 업로드하도록 수정
  .github/workflows/CICD.yml
  build.gradle
Labels: :bug:bug

#101 🐛 [fix] bootJar에 Main-Class 명시하여 실행 가능 jar 생성
  build.gradle
Labels: :bug:bug

#103 🔧 [update] gradle file
  build.gradle
Labels: :bug:bug

#106 🐛 [fix(cicd)] Docker 태그 오류 수정
  .github/workflows/CICD.yml
Labels: :bug:bug

#107 Bug/#93
  .github/workflows/CICD.yml
Labels: :bug:bug

#108 🐛 [fix] CICD.yml 수정 ( CI job에 output 선언 )
  .github/workflows/CICD.yml
Labels: :bug:bug

#116 🐛 [fix] CICD.yml 수정
  Dockerfile
Labels: :bug: Bug

#117 🐛 [fix] CICD.yml 수정
  .github/workflows/CICD.yml
  Dockerfile
Labels: :bug: Bug

#121 🐛 [fix] CI/CD 파이프라인 수정: Dockerfile 경로 수정 및 Docker 빌드 프로세스 개선
  .github/workflows/CICD.yml
Labels: :bug: Bug

#123 🐛 [fix(cicd)] CI/CD 파이프라인 수정 - buid/libs check , Docker build 전 JAR file 검증
  .github/workflows/CICD.yml
  Dockerfile
Labels: :bug: Bug, :earth_asia: Deploy

#126 🐛 [fix] CICD.yml 경로 수정
  .github/workflows/CICD.yml
  Dockerfile
Labels: :bug: Bug

#127 🐛 [fix] CICD 수정
  .github/workflows/CICD.yml
  Dockerfile
Labels: :bug: Bug

#128 🐛 [fix] Dockerfile 및 CICD.yml 수정
  .github/workflows/CICD.yml
  Dockerfile
Labels: :bug: Bug

#130 🐛 [fix] Dockfile 및 CICD.yml 수정
  .github/workflows/CICD.yml
  Dockerfile
Labels: :bug: Bug, :earth_asia: Deploy

#131 🐛 [fix] Dockerfile Entrypoint 수정
  Dockerfile
  docker-compose.yml
Labels: :bug: Bug, :earth_asia: Deploy

#132 🐛 [fix] Dockerfile, gradle, cicd.yml 수정
  .github/workflows/CICD.yml
  Dockerfile
  build.gradle
Labels: :bug: Bug, :earth_asia: Deploy

#134 🐛 [fix] CICD 파이프라인 수정
  .github/workflows/CICD.yml
  build.gradle
Labels: :bug: Bug

#135 🐛 [fix] Spring Boot 애플리케이션 실행 구조 개선
  .github/workflows/CICD.yml
  Dockerfile
  build.gradle
Labels: :bug: Bug
